### ISSUE TITLE
utkscan - Report when spill has different number of modules than map

### ISSUE THREAD

**Issue by ksmith0** [pixie16/paass#103]
Many users get tripped up by the requirement to have a channel in the last module defined in the map. It would be good to report a message to the user that the value of modules differs and that the spill is ignored due to that reason.

**Comment by spaulaus** [comment]
The scan no longer requires that you have all of the channels defined in the map. This requirement and the message were necessary at the level of unpacking the data in pixie_scan since the event building was different. The Unpacker now handles these things automatically, and this check (and message) no longer even exist in the software. 

However, since it was early morning when I visited this. I do agree that it might be helpful for the Unpacker to give some diagnostic information such as this. I do not know **when** that information should be provided, since you could potentially have modules that have channels that trigger so infrequently that you do not get information about them until much later.

**Comment by ksmith0** [comment]
At the moment a spill always writes out something for every module connected even if there are no triggers. So any spill should provide some information which can help validate the map.

**Comment by spaulaus** [comment]
I don't see how this will help validate the map. The purpose of the map is to provide context to what we connected to a particular channel. If module 10 is present but never has a trigger, do I care about there being a word in the spill telling me that the module didn't have any triggers?

We often remove channels that are present in the data when we do not wish to analyze them. If there is nothing meaningful in the data stream for a given module, then there's no reason to spend time validating that it exists in the map. 

For example, in the data set that I took at MSU. There are 10 modules in the system. I have a trigger in M0C0 and VANDLE in M 1-6 C 0-16. No other signals are cabled or present in the system. Do I really care if the spill contains just the "header" information about module 10? Not particularly. Will I pay attention to a warning that module 10 isn't in the map? Absolutely not. 

Another example is the gamma-ray analysis of the ORNL 2016 data set. All of the information related to VANDLE and the high res beta were stripped out of the Map node. The user does not need to be prompted that there is data in those channels, they know it and adjusted their map file to compensate for that. 

If the user is really keen on making sure they have the necessary information then you can set the Verbosity flag in the Map node to true and receive an entire print-out of what was read by the map, by default we simply produce a summary:. 

```
Initializing scan.................................................
   * First buffer at 1432523497 sys time                         
   * 1 detector types are used in this analysis and are named:   
       * pspmt                                                   
   * 2 detector subtypes are used in this analysis and are named:
       * anode dynode                                            
   * processor PspmtProcessor initialized operating on 1 detector
      type(s).                                                   
   * processor E14060PRocessor initialized operating on 1 detecto
     r type(s). 
```

I do not think that the data can validate the map since the Unpacker, or the scan does not know what the user intended when they wrote it. The construction of the Map node depends highly upon the analysis goals. If we print a message every time we ignore something from a spill we would get swamped with messages in situations described above. 

I once again reiterate that this is no longer a requirement by utkscan since the Unpacker has superseded the PixieStd.cpp. This issue is _only_ present in pixie_scan.

**Comment by ksmith0** [comment]
I agree with this with the obvious exception that if a module is not present in the data, but is present in the map then an error is thrown.

Is this really no longer in utkscan, even with pixie_scan? The biggest problem we had with this was that pixie_scan required all modules to be declared otherwise the spill was rejected. If this is no longer the case then we only need to worry about the first situation I mentioned in this comment.

**Comment by spaulaus** [comment]
Right, this error was thrown only during the unpacking and spill reconstruction process. I have run numerous files with data taken recently and have seen no issues. 

If I recall @cthornsb's presentation from the workshop, if no triggers are present there's spill still has two words for the module, the number, and a -2 to say that it's empty. Is that correct? If that is the case, then the first spill can be used to validate the map, and one can return before any meaningful processing gets done.

**Comment by ksmith0** [comment]
Nearly correct. An empty module is written out as a vsn and size of module data in words which would be 2.

The method for validation is correct. If this was done only once, one could also include a little warning if the map doesn't cover all the module. then the user could find it if they had problems, but otherwise not be overwhelmed with messages.

**Comment by spaulaus** [comment]
Then I think the validation should go as follows. We obtain the first spill, read in the map, and then compare the number of modules. If they are different then we print a warning to the screen; if they are the same then we do nothing. 

This will have to be included on the UtkUnpacker side since this will be specific to this program.

**Comment by spaulaus** [comment]
I will revise this. It seems that this check is still performed, since I just received it while reading in a PLD. We will have to investigate before we make some kind of decision.
