### ISSUE TITLE
utkscan Raw DAMM output only 14 bit

### ISSUE THREAD

**Issue by ksmith0** [pixie16/paass#115]
The filter energies are stored as 16 bit values, but only 14 bits are displayed in the DAMM output from utkscan. In `DetectorDriver::DeclarePlots` Extending the raw histogram declaration even just to 15 bit (`SF`)

``` c++
 DeclareHistogram1D(D_RAW_ENERGY + i, SF,
                                  ("RawE " + idstr.str()).c_str() );
```

causes an error to appear in DAMM

```
DNOR range exceeds data for N-file,  ID =       0
```

If DAMM is not capable of displaying the full value, then it should be divided down to fit in the plot.

**Comment by spaulaus** [comment]
No, this decision has been made in the past. The raws are not divided down, as this defeats the purpose of having "raw" histograms. You can use a calibration to fix this issue.

**Comment by ksmith0** [comment]
What do you mean divide down? At the moment, I cannot see the peak from my Cs137 data as it is off scale.

**Comment by spaulaus** [comment]
You want to put in an energy contraction. This was removed from the software since it was causing all kinds of havoc when people would forget that there was a contraction while trying to perform functions like calibration. 

If you want the spectrum to fit into DAMM's range you can add an energy calibration to the channel and then view it in the calibrated histogram.

**Comment by ksmith0** [comment]
Why can't you simply plot the Raw histogram as energy / 4? You don't need to actually scale the energy value. If it wont be fixed it seems that the raws are less useful for me then I would have expected.

**Comment by spaulaus** [comment]
As mentioned you can use the calibrated histogram to achieve the desired result. . 

The choice was made to ignore this since it caused too many problems, even after users were explicitly told about the compression factor. In addition, is can cause issues with users trying to output information to ROOT (where this is not an issue at all).
