### ISSUE TITLE
On dev - Unpacker throws error for missing VSN.

### ISSUE THREAD

**Issue by akeeler** [pixie16/paass#289]
After updating my config file per the wiki guidelines, I see the following error when I try to run utkscan:

`[IDLE] Waiting for Unpacker . . .                                                                         what():  Unpacker::ReadBuffer - Unable to locate VSN = 0 in the maskMap.  Ensure that it's defined in your configuration file!`

I've located where the throw is happening in the unpacker, but the current documentation doesn't shed any light on what specifically is happening to cause the throw, nor on how to fix it.

**Comment by akeeler** [comment]
here is the current map node.  This is for test data where we aren't taking any traces.
```
    <Map verbose_calibration="False" verbose_map="False" verbose_walk="False">
        <Module number="1" firmware="34300" frequency="250">
            <Channel number="0" type="pspmt" subtype="dynode"></Channel>
            <Channel number="1" type="pspmt" subtype="anode" tags="xa"></Channel>
	    <Channel number="2" type="pspmt" subtype="anode" tags="xb"></Channel>
	    <Channel number="3" type="pspmt" subtype="anode" tags="ya"></Channel>
	    <Channel number="4" type="pspmt" subtype="anode" tags="yb"></Channel>
        </Module>
    </Map>

```

**Comment by spaulaus** [comment]
This means that Module 0 (VSN =0) existed in the physical configuration but you didn't define it in the Map. This change was made to close Issue #103. Since the data file has no information about the firmware or modules, we have to provide that information to the scan. You have provided that information for Module 1 (VSN=1) but not for Module 0. 

If memory serves, you can bypass this by removing the firmware / frequency specification in the map and using the command line to define this. 

I will also note that the error tells you how to fix the issue : 

> Ensure that it's defined in your configuration file!

I will also say that the convention of labeling things with a VSN (virtual serial number??) adds confusion to the whole process for the end users.
